version: '3'
services:
  db_pg_ava_example_dev:
    hostname: db_pg_ava_example_dev
    container_name: db_pg_ava_example_dev
    image: postgres:14.6
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./data/db/:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        ipv4_address: ${IP_ADDRESS}


  pgadmin_ava_example_dev:
    hostname: pgadmin_ava_example_dev
    container_name: pgadmin_ava_example_dev
    image: dpage/pgadmin4
    restart: always
    user: '$UID:$GID'
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default: # here we set the network name
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET}